openapi: 3.0.1
info:
  version: '1.0'
  title: Business Accounting Partners API
  description: "As a Revolut Business customer with a Business Account, you can use the Business API to automate your own business processes.\nSave time, reduce your costs, and avoid errors by using the Business API. \n\n:::tip[Before you get started]\nTo learn more about the Business API and its features, check the [**user guides**](https://developer.revolut.com/docs/guides/manage-accounts/introduction).\n\nYou can reach them at any time from the main navigation bar **→ Guides → Business**.\n:::\n\nYou can view accounts, manage counterparties, make payments or currency exchanges without manual effort in the Web UI:\n\n- Accounting: [Account management](https://developer.revolut.com/docs/api/business#get-account), [Accounting settings](https://developer.revolut.com/docs/api/business#tag-accounting), [Expense management](https://developer.revolut.com/docs/api/business#get-expense), [Transactions](https://developer.revolut.com/docs/api/business#get-transactions) \n- Payments: \n  - [Counterparty management](https://developer.revolut.com/docs/api/business#get-counterparties)\n  - Payment management: [Payment drafts](https://developer.revolut.com/docs/api/business#delete-payment-draft), [Payout links](https://developer.revolut.com/docs/api/business#get-payout-link), [Transfers](https://developer.revolut.com/docs/api/business#tag-transfers)\n  - [Foreign exchange](https://developer.revolut.com/docs/api/business#tag-foreign-exchange)\n- Business team: [Card management](https://developer.revolut.com/docs/api/business#delete-card), [Card invitation management](https://developer.revolut.com/docs/api/business#update-card-invitation), [Team member management](https://developer.revolut.com/docs/api/business#delete-team-member)\n- Developer tools: [Sandbox simulations](https://developer.revolut.com/docs/api/business#tag-simulations), [Webhook management](https://developer.revolut.com/docs/api/business#tag-webhooks-v2)\n\nTo see the reference for the specific endpoints and operations of this API, browse the menu on the left.\n\n### Test the Business API\n\nYou can test the Business API in Postman by forking this collection:\n\n[![View in Postman](https://run.pstmn.io/button.svg)](https://www.postman.com/revolut-api/workspace/revolut-developers/overview)"
  contact: {}
servers:
- url: https://b2b.revolut.com/api/1.0
  description: Production server (uses live data)
- url: https://sandbox-b2b.revolut.com/api/1.0
  description: Sandbox server (uses test data)
tags:
- name: Partners
  description: 'The **Partners** endpoints let you poll different exchange rates, display them on your website and compare them with other providers.


    For more details, see the guides: [Leverage the Crypto Ramp API](https://developer.revolut.com/docs/guides/crypto-ramp/tutorials/use-the-api).'
paths:
  /config:
    get:
      operationId: retrieve-configuration
      tags:
      - Partners
      summary: Retrieve configuration
      description: 'Retrieve Revolut Ramp configuration, such as available fiat currencies and crypto tokens with corresponding limits and supported countries.


        For more information, see the guides: [Leverage the Crypto Ramp API -> Get your configuration details](https://developer.revolut.com/docs/guides/crypto-ramp/tutorials/use-the-api#get-your-configuration-details).'
      parameters:
      - $ref: '#/components/parameters/XApiKey'
      security:
      - AccessToken: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
              example:
                version: 1.0.0
                countries:
                - GB
                - US
                - PT
                - FR
                fiat:
                - currency: GBP
                  min_limit: 50
                  max_limit: 500
                - currency: USD
                  min_limit: 60
                  max_limit: 600
                - currency: EUR
                  min_limit: 60
                  max_limit: 600
                crypto:
                - id: BTC
                  currency: BTC
                  blockchain: BITCOIN
                - id: ETH
                  currency: ETH
                  blockchain: ETHEREUM
                - id: USDT-ETH
                  currency: USDT
                  blockchain: ETHEREUM
                  smartContractAddress: 1.2488751460129641e+48
                - id: USDT-OPTIMISM
                  currency: USDT
                  blockchain: OPTIMISM
                  smartContractAddress: 8.488563199836144e+47
                feePercentages:
                - 0.8
                - 1
                payment_methods:
                - card
                - revolut
                - apple-pay
                - google-pay
        '401':
          description: Unauthorized
        '429':
          description: Too Many Requests
        '500':
          $ref: '#/components/responses/ServerErrorResponse'
        '503':
          $ref: '#/components/responses/DisabledByKillSwitchErrorResponse'
  /quote:
    get:
      operationId: retrieve-an-order-quote
      tags:
      - Partners
      summary: Retrieve an order quote
      description: 'Retrieve an order quote representing current exchange rate, total crypto amount and fees.

        Use it to display potential exchange rate to your customer.


        For more information, see the guides: [Leverage the Crypto Ramp API -> Get an order quote](https://developer.revolut.com/docs/guides/crypto-ramp/tutorials/use-the-api#get-an-order-quote).'
      security:
      - AccessToken: []
      parameters:
      - in: query
        name: fiat
        description: The [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) code of the selected fiat currency to use for the purchase.
        required: true
        schema:
          $ref: '#/components/schemas/Currency'
      - in: query
        name: amount
        description: The fiat amount to exchange for crypto.
        required: true
        schema:
          type: number
          format: float
      - in: query
        name: crypto
        description: The ID of the crypto token to purchase, obtained from the [`/config`](https://developer.revolut.com/docs/api/crypto-ramp#retrieve-configuration) endpoint.
        required: true
        schema:
          type: string
      - in: query
        name: payment
        description: The selected [payment option](https://developer.revolut.com/docs/guides/crypto-ramp/introduction-to-revolut-ramp/coverage-and-other-details/payment-options).
        required: true
        schema:
          type: string
          enum:
          - card
          - revolut
          - apple-pay
          - google-pay
      - in: query
        name: region
        description: The [ISO 3166 Alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code of the country of residence of the customer (end user) ordering the exchange.
        required: true
        schema:
          $ref: '#/components/schemas/CountryCode'
      - in: query
        name: feePercentage
        description: The fee percentage that will be applied for the order as partner fee.
        required: false
        schema:
          type: number
          format: float
      - in: query
        name: walletAddress
        description: The address of the crypto wallet into which the purchased token should be transferred.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
              example:
                service_fee:
                  amount: 3.76
                  currency: USD
                network_fee:
                  amount: 0.91
                  currency: USD
                crypto:
                  amount: 0.10604352
                  currencyId: ETH
                partner_fee:
                  amount: 0.77
                  currency: USD
        '400':
          $ref: '#/components/responses/BadRequestErrorResponse'
        '401':
          description: Unauthorized
        '429':
          description: Too Many Requests
        '500':
          $ref: '#/components/responses/ServerErrorResponse'
        '503':
          $ref: '#/components/responses/DisabledByKillSwitchErrorResponse'
  /buy:
    get:
      operationId: retrieve-a-redirect-url
      tags:
      - Partners
      summary: Retrieve a redirect URL
      description: 'Retrieve a redirect URL to the Ramp app widget for provided buy parameters. Use it to redirect the customer to Revolut Ramp to make the purchase.


        :::note

        The `amount` in the Redirect URL is provided in minor currency units.

        For example, GBP 12.00 is represented as `1200`.

        :::


        For more information, see the guides: [Leverage the Crypto Ramp API -> Get a Revolut Ramp Redirect URL](https://developer.revolut.com/docs/guides/crypto-ramp/tutorials/use-the-api#get-a-revolut-ramp-redirect-url).'
      security:
      - AccessToken: []
      parameters:
      - $ref: '#/components/parameters/XApiKey'
      - in: query
        name: fiat
        description: The [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) code of the selected fiat currency to use for the purchase.
        required: true
        schema:
          $ref: '#/components/schemas/Currency'
      - in: query
        name: amount
        description: The fiat amount to exchange for crypto.
        required: true
        schema:
          type: number
          format: float
      - in: query
        name: crypto
        description: The ID of the crypto token to purchase, obtained from the [`/config`](https://developer.revolut.com/docs/api/crypto-ramp#retrieve-configuration) endpoint.
        required: true
        schema:
          type: string
      - in: query
        name: payment
        description: The selected [payment option](https://developer.revolut.com/docs/guides/crypto-ramp/introduction-to-revolut-ramp/coverage-and-other-details/payment-options).
        required: true
        schema:
          type: string
          enum:
          - card
          - revolut
          - apple-pay
          - google-pay
      - in: query
        name: region
        description: The [ISO 3166 Alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code of the country of residence of the customer (end user) ordering the exchange.
        required: true
        schema:
          $ref: '#/components/schemas/CountryCode'
      - in: query
        name: wallet
        description: The address of the crypto wallet into which to transfer the purchased token.
        required: true
        schema:
          type: string
      - in: query
        name: orderId
        description: 'The external identifier of the order to be made.

          Should be either UUID or ULID.'
        schema:
          type: string
          format: uuid | ulid
      - in: query
        name: feePercentage
        description: The fee percentage that will be applied for the order as partner fee.
        required: false
        schema:
          type: number
          format: float
      - in: query
        name: partnerRedirectUrl
        description: The URL to which to redirect the customer after the purchase – for example, your website. If not provided, the customer is shown transaction result in Revolut Ramp.
        schema:
          type: string
      - in: query
        name: additionalProperties
        description: "A prefix that allows passing arbitrary key-value pairs. \nFor each pair, the prefix and key should be separated by `.`.\n\nIf such additional properties are provided, when you call the [`/orders`](https://developer.revolut.com/docs/api/crypto-ramp#retrieve-all-orders) endpoint, they are returned along with the order details."
        schema:
          type: string
          pattern: additionalProperties.[key]=[value]
      responses:
        '200':
          description: 'The requested redirect URL


            :::note

            The `amount` in the Redirect URL is provided in minor currency units.

            For example, GBP 12.00 is represented as `1200`.

            :::'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RampRedirectUrl'
              example:
                ramp_redirect_url: https://ramp.revolut.com?fiatCurrency=GBP&amount=12345&cryptoCurrency=ETH&walletAddress=0x96e2B7Bf479f84e7A0a94f0620290B7D3E08f5EF&countryCode=GB&partnerId=a01798bc-7f0b-14ed-a12b-0e3fac1209ad&externalOrderId=2d1769bc-7aab-92ed-a10b-0232ac12090d&disableFiatAmount=true&disableCryptoCurrency=true&disableWalletAddress=true&disableCountryCode=true&partnerRedirectUrl=https%3A%2F%2Fcrypto.partner.com%2Forder%3ForderId%3D2d1769bc-7aab-92ed-a10b-0232ac12090d
        '400':
          $ref: '#/components/responses/BadRequestErrorResponse'
        '401':
          description: Unauthorized
        '429':
          description: Too Many Requests
        '500':
          $ref: '#/components/responses/ServerErrorResponse'
        '503':
          $ref: '#/components/responses/DisabledByKillSwitchErrorResponse'
  /orders/{order_id}:
    get:
      operationId: retrieve-an-order
      tags:
      - Partners
      summary: Retrieve an order
      description: 'Retrieve an order by `order_id` provided in the path and the `wallet` address provided as a query parameter.


        For more information, see the guides: [Leverage the Crypto Ramp API -> Get an order](https://developer.revolut.com/docs/guides/crypto-ramp/tutorials/use-the-api#get-an-order).'
      security:
      - AccessToken: []
      parameters:
      - $ref: '#/components/parameters/XApiKey'
      - in: path
        name: order_id
        description: 'The external identifier of the order to retrieve.

          Should be either UUID or ULID.'
        required: true
        schema:
          type: string
          format: uuid | ulid
      - in: query
        name: wallet
        description: The address of the crypto wallet into which the token transfer was ordered.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
              example:
                id: a01868cc-71ab-d2ed-a10b-0a32ac1c0b02
                fiat:
                  amount: 101.22
                  currency: USD
                crypto:
                  amount: 0.10604352
                  currencyId: ETH
                fees:
                  ramp_fee:
                    amount: 2.75
                    currency: USD
                  partner_fee:
                    amount: 1.01
                    currency: USD
                  network_fee:
                    amount: 0.91
                    currency: USD
                exchange_rate: 0.00089088
                payment: card
                created_at: '2022-12-26T11:32:10Z'
                updated_at: '2022-12-26T11:33:54Z'
                status: COMPLETED
                wallet: '0x96e2B7Bf479f84e7A0a94f0620290B7D3E08f5EF'
                transaction_hash: 76cfb3b4f0acd595fa5b24036e86fd21d3c7b9887b2c8e3d4007598e4cbe6957
                fees_partner_currency:
                  ramp_fee:
                    amount: 2.35
                    currency: EUR
                  partner_fee:
                    amount: 0.9
                    currency: EUR
                  network_fee:
                    amount: 0.78
                    currency: EUR
        '400':
          $ref: '#/components/responses/BadRequestErrorResponse'
        '401':
          description: Unauthorized
        '404':
          $ref: '#/components/responses/NotFoundErrorResponse'
        '429':
          description: Too Many Requests
        '500':
          $ref: '#/components/responses/ServerErrorResponse'
        '503':
          $ref: '#/components/responses/DisabledByKillSwitchErrorResponse'
  /orders:
    get:
      operationId: retrieve-all-orders
      tags:
      - Partners
      summary: Retrieve all orders
      description: 'Retrieve all orders by date range.


        The results are sorted chronologically by the `created_at` date (i.e. oldest first).


        For more information, see the guides: [Leverage the Crypto Ramp API -> Get all orders](https://developer.revolut.com/docs/guides/crypto-ramp/tutorials/use-the-api#get-all-orders).'
      security:
      - AccessToken: []
      parameters:
      - $ref: '#/components/parameters/XApiKey'
      - in: query
        name: start
        description: 'The earliest date for the order creation date range (inclusive) in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.


          In other words, the "oldest" order creation date you are interested in.'
        required: true
        schema:
          type: string
          format: date
      - in: query
        name: end
        required: true
        schema:
          type: string
          format: date
        description: 'The latest date for the order creation date range (inclusive) in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.


          In other words, the "most recent" order creation date you are interested in.'
      - in: query
        name: skip
        schema:
          type: integer
          format: int32
          default: 0
        description: 'The number of orders to skip at the beginning of the range when fetching orders (sorted by creation date, oldest first).


          This means that if you set `skip=3`, the first three orders are skipped, and the list of orders that you get as a result will start with the order that would normally be 4th on the list.'
      - in: query
        name: limit
        schema:
          type: integer
          format: int32
          default: 100
          minimum: 1
          maximum: 1000
        description: 'The maximum number of orders to fetch from the given range.

          Must be between `1` and `1000` (inclusive).

          Default value is `100`.'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Orders'
              example:
              - $ref: '#/components/schemas/Order/example'
              - id: 3afb8396-1cee-4562-bd0f-5aea5e674da9
                fiat:
                  amount: 11.55
                  currency: GBP
                crypto:
                  amount: 0.00889211
                  currency: ETH
                fees:
                  ramp_fee:
                    amount: 2.4
                    currency: GBP
                  partner_fee:
                    amount: 0.8
                    currency: GBP
                  network_fee:
                    amount: 0.75
                    currency: GBP
                exchange_rate: 0.00076988
                payment: card
                created_at: '2022-01-03T08:44:38Z'
                updated_at: '2022-01-14T11:37:02Z'
                status: COMPLETED
                wallet: 1PUyin99nPbdm3NTa2BViJ1JsEe8e8iAcs
                transaction_hash: d276938168a948e8eb5c99515baf9fb209c00b24c9521f0d4970c5e9f4dcc886
                fees_partner_currency:
                  ramp_fee:
                    amount: 2.89
                    currency: EUR
                  partner_fee:
                    amount: 0.97
                    currency: EUR
                  network_fee:
                    amount: 0.91
                    currency: EUR
        '401':
          description: Unauthorized
        '429':
          description: Too Many Requests
        '500':
          $ref: '#/components/responses/ServerErrorResponse'
        '503':
          $ref: '#/components/responses/DisabledByKillSwitchErrorResponse'
components:
  schemas:
    MoneyCryptoId:
      type: object
      required:
      - amount
      - currencyId
      properties:
        amount:
          type: number
          format: float
          description: The amount.
        currencyId:
          $ref: '#/components/schemas/CurrencyCryptoId'
      example:
        amount: 100
        currencyId: USDT-ETH
    Currency:
      type: string
      description: The fiat currency [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) code or [cryptocurrency code](https://en.wikipedia.org/wiki/List_of_cryptocurrencies).
      examples:
        fiatCurrency:
          summary: Fiat currency
          value: GBP
        cryptoCurrency:
          summary: Cryptocurrency
          value: ETH
    MoneyFiat:
      type: object
      required:
      - amount
      - currency
      properties:
        amount:
          type: number
          format: float
          description: The amount.
        currency:
          $ref: '#/components/schemas/CurrencyFiat'
      example:
        amount: 100
        currency: USD
    Order:
      type: object
      description: Fiat to crypto exchange order
      required:
      - id
      - fiat
      - crypto
      - fees
      - exchange_rate
      - payment
      - created_at
      - updated_at
      - status
      - wallet
      - fees_partner_currency
      properties:
        id:
          type: string
          format: uuid
          description: The external UUID of the order.
        fiat:
          $ref: '#/components/schemas/MoneyFiat'
          description: The fiat amount that the customer paid for the crypto (excluding fees).
        crypto:
          $ref: '#/components/schemas/MoneyCryptoId'
          description: The crypto amount that the customer received.
        fees:
          type: object
          description: The fees for the order.
          required:
          - ramp_fee
          - partner_fee
          - network_fee
          properties:
            ramp_fee:
              $ref: '#/components/schemas/MoneyFiat'
              description: Revolut Ramp fee.
            partner_fee:
              $ref: '#/components/schemas/MoneyFiat'
              description: Partner fee.
            network_fee:
              $ref: '#/components/schemas/MoneyFiat'
              description: Crypto network fee.
        exchange_rate:
          type: number
          format: float
          description: The exchange rate for the order.
        payment:
          type: string
          enum:
          - card
          - revolut
          - apple-pay
          - google-pay
          description: The [payment method](https://developer.revolut.com/docs/guides/crypto-ramp/introduction-to-revolut-ramp/coverage-and-other-details/payment-options) used for the purchase.
        created_at:
          type: string
          format: date-time
          description: The UTC date and time of order creation in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
        updated_at:
          type: string
          format: date-time
          description: The UTC date and time of order update in the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
        status:
          type: string
          enum:
          - AWAITING_PAYMENT
          - PROCESSING
          - COMPLETED
          - FAILED
          description: The state of order processing.
        fail_reason:
          type: string
          enum:
          - PAYMENT_NOT_RECEIVED
          - PAYMENT_DECLINED
          - CRYPTO_WITHDRAWAL_FAILED
          - OTHER
          description: The reason why the order failed.
        wallet:
          type: string
          description: The address of the crypto wallet into which the crypto transfer was ordered.
        transaction_hash:
          type: string
          description: 'The blockchain transaction hash.

            Absent if no crypto transaction has been created yet.

            Always present if order is in the `COMPLETED` state.'
        additionalProperties:
          type: object
          description: The additional properties passed in the call to the [`/buy`](https://developer.revolut.com/docs/api/crypto-ramp#retrieve-a-redirect-url) endpoint under the `additionalProperties.*` query parameter(s), if such properties were provided.
          additionalProperties:
            type: string
        fees_partner_currency:
          type: object
          description: The fees converted to the partner's currency.
          required:
          - ramp_fee
          - partner_fee
          - network_fee
          properties:
            ramp_fee:
              $ref: '#/components/schemas/MoneyFiat'
              description: Revolut Ramp fee.
            partner_fee:
              $ref: '#/components/schemas/MoneyFiat'
              description: Partner fee.
            network_fee:
              $ref: '#/components/schemas/MoneyFiat'
              description: Crypto network fee.
      example:
        id: a01868cc-71ab-d2ed-a10b-0a32ac1c0b02
        fiat:
          amount: 101.22
          currency: USD
        crypto:
          amount: 0.10604352
          currencyId: ETH
        fees:
          ramp_fee:
            amount: 2.75
            currency: USD
          partner_fee:
            amount: 1.01
            currency: USD
          network_fee:
            amount: 0.91
            currency: USD
        exchange_rate: 0.00089088
        payment: card
        created_at: '2022-12-26T11:32:10Z'
        updated_at: '2022-12-26T11:33:54Z'
        status: COMPLETED
        wallet: '0x96e2B7Bf479f84e7A0a94f0620290B7D3E08f5EF'
        transaction_hash: 76cfb3b4f0acd595fa5b24036e86fd21d3c7b9887b2c8e3d4007598e4cbe6957
        fees_partner_currency:
          ramp_fee:
            amount: 2.35
            currency: EUR
          partner_fee:
            amount: 0.9
            currency: EUR
          network_fee:
            amount: 0.78
            currency: EUR
    BadRequestError:
      type: object
      description: Thrown when request parameter field is invalid
      required:
      - message
      properties:
        message:
          type: string
          description: Specifies the invalid parameter that was provided by the user.
      example:
        message: Invalid field 'FieldName'
    CurrencyCryptoCode:
      type: string
      description: The [cryptocurrency code](https://en.wikipedia.org/wiki/List_of_cryptocurrencies).
      example: ETH
    Quote:
      type: object
      description: The exchange price between fiat and crypto currencies (including fees).
      required:
      - service_fee
      - network_fee
      - crypto
      - partner_fee
      properties:
        service_fee:
          $ref: '#/components/schemas/MoneyFiat'
          description: 'The sum of Revolut Ramp fee and Partner fee.


            :::note

            The Partner fee is also provided separately in the `partner_fee` parameter.

            :::'
        network_fee:
          $ref: '#/components/schemas/MoneyFiat'
          description: Crypto network fee.
        crypto:
          $ref: '#/components/schemas/MoneyCryptoId'
          description: Crypto amount that the customer receives in the case of a successful exchange.
        partner_fee:
          $ref: '#/components/schemas/MoneyFiat'
          description: 'Partner fee.


            :::note

            This Partner fee is also included in the `service_fee` value, which represents the total sum of Partner fee and Revolut Ramp fee.

            :::'
      example:
        service_fee:
          amount: 3.76
          currency: USD
        network_fee:
          amount: 0.91
          currency: USD
        crypto:
          amount: 0.10604352
          currencyId: ETH
        partner_fee:
          amount: 0.77
          currency: USD
    DisabledByKillSwitchError:
      type: object
      description: Thrown when endpoint is disabled by Kill Switch.
      required:
      - message
      properties:
        message:
          type: string
          description: The message displayed to the user when endpoint is disabled by Kill Switch.
      example:
        message: Service is not available
    Blockchain:
      type: string
      description: The cryptocurrency blockchain/network.
      enum:
      - BITCOIN
      - RIPPLE
      - BITCOINCASH
      - LITECOIN
      - ETHEREUM
      - DOGECOIN
      - CARDANO
      - STELLAR
      - POLKADOT
      - SOLANA
      - AVALANCHE
      - EOS
      - TEZOS
      - DASH
      - ALGORAND
      - CELO
      - SMARTCHAIN
      - POLYGON
      - FANTOM
      - OPTIMISM
      - COSMOS
      - KUSAMA
      - ETHEREUMCLASSIC
      - ETHEREUMPOW
      - HEDERAHASHGRAPH
      - TRON
      - KAVA
      - NEAR
      - SONGBIRD
      - FLARE
      - CELESTIA
      - BASE
    CurrencyCryptoId:
      type: string
      description: The ID of the currency, obtained from the [`/config`](https://developer.revolut.com/docs/api/crypto-ramp#retrieve-configuration) endpoint.
      example: USDT-ETH
    NotFoundError:
      type: object
      description: Thrown when resource can't be found
      required:
      - message
      properties:
        message:
          type: string
          description: The message displayed to the user when resource cannot be found.
      example:
        message: Not found
    CurrencyFiat:
      type: string
      format: ISO 4217
      description: The fiat currency [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) code.
      example: GBP
    RampRedirectUrl:
      type: object
      description: Redirect URL to Ramp app widget
      required:
      - ramp_redirect_url
      properties:
        ramp_redirect_url:
          type: string
          format: uri
          description: The URL to Revolut Ramp to which to redirect the customer for the purchase.
      example:
        ramp_redirect_url: https://ramp.revolut.com?fiatCurrency=GBP&amount=12345&cryptoCurrency=ETH&walletAddress=0x96e2B7Bf479f84e7A0a94f0620290B7D3E08f5EF&countryCode=GB&partnerId=a01798bc-7f0b-14ed-a12b-0e3fac1209ad&externalOrderId=2d1769bc-7aab-92ed-a10b-0232ac12090d&disableFiatAmount=true&disableCryptoCurrency=true&disableWalletAddress=true&disableCountryCode=true&partnerRedirectUrl=https%3A%2F%2Fcrypto.partner.com%2Forder%3ForderId%3D2d1769bc-7aab-92ed-a10b-0232ac12090d
    Orders:
      type: array
      items:
        $ref: '#/components/schemas/Order'
      example:
      - $ref: '#/components/schemas/Order/example'
      - id: 3afb8396-1cee-4562-bd0f-5aea5e674da9
        fiat:
          amount: 11.55
          currency: GBP
        crypto:
          amount: 0.00889211
          currency: ETH
        fees:
          ramp_fee:
            amount: 2.4
            currency: GBP
          partner_fee:
            amount: 0.8
            currency: GBP
          network_fee:
            amount: 0.75
            currency: GBP
        exchange_rate: 0.00076988
        payment: card
        created_at: '2022-01-03T08:44:38Z'
        updated_at: '2022-01-14T11:37:02Z'
        status: COMPLETED
        wallet: 1PUyin99nPbdm3NTa2BViJ1JsEe8e8iAcs
        transaction_hash: d276938168a948e8eb5c99515baf9fb209c00b24c9521f0d4970c5e9f4dcc886
        fees_partner_currency:
          ramp_fee:
            amount: 2.89
            currency: EUR
          partner_fee:
            amount: 0.97
            currency: EUR
          network_fee:
            amount: 0.91
            currency: EUR
    UnexpectedError:
      type: object
      description: Thrown when an unexpected error happens.
      required:
      - errorId
      - timestamp
      properties:
        errorId:
          type: string
          format: uuid
          description: The UUID of the unexpected error that has occurred.
        timestamp:
          type: integer
          format: int64
          description: The timestamp of when the error happened.
      example:
        errorId: 201768bc-7fab-12ed-a1bb-0232ac120902
        timestamp: 1671481582960
    CountryCode:
      type: string
      description: The [ISO 3166 Alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code of the country.
      example: GB
    Config:
      type: object
      required:
      - version
      - countries
      - fiat
      - crypto
      - payment_methods
      properties:
        version:
          type: string
          description: The Revolut Ramp configuration version.
        countries:
          type: array
          description: The list of client countries supported by Ramp – for your customer to be able to use Revolut Ramp, they must be resident in one of those countries.
          items:
            $ref: '#/components/schemas/CountryCode'
        fiat:
          description: The supported fiat currencies and limits.
          type: array
          items:
            type: object
            description: The supported fiat currency and limits.
            required:
            - currency
            - min_limit
            - max_limit
            properties:
              currency:
                $ref: '#/components/schemas/CurrencyFiat'
                description: The [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) code of the supported currency.
              min_limit:
                type: number
                format: float
                description: The minimum allowed amount.
              max_limit:
                type: number
                format: float
                description: The maximum allowed amount.
        crypto:
          type: array
          description: The list of cryptocurrencies supported by Revolut Ramp.
          items:
            type: object
            description: Supported crypto currency.
            required:
            - id
            - currency
            - blockchain
            properties:
              id:
                type: string
                description: 'The unique identifier of the crypto currency-blockchain pair.

                  Should be used throughout the API to reference the specific crypto.'
                example: USDT-ETH
              currency:
                $ref: '#/components/schemas/CurrencyCryptoCode'
              blockchain:
                $ref: '#/components/schemas/Blockchain'
              smartContractAddress:
                type: string
                description: The smart contract address. Returned only for tokens.
        feePercentages:
          description: The list of fee percentages that can be applied for the order as partner fee.
          type: array
          items:
            type: number
            format: float
        payment_methods:
          description: The list of available payment methods.
          type: array
          items:
            type: string
            enum:
            - card
            - revolut
            - apple-pay
            - google-pay
      example:
        version: 1.0.0
        countries:
        - GB
        - US
        - PT
        - FR
        fiat:
        - currency: GBP
          min_limit: 50
          max_limit: 500
        - currency: USD
          min_limit: 60
          max_limit: 600
        - currency: EUR
          min_limit: 60
          max_limit: 600
        crypto:
        - id: BTC
          currency: BTC
          blockchain: BITCOIN
        - id: ETH
          currency: ETH
          blockchain: ETHEREUM
        - id: USDT-ETH
          currency: USDT
          blockchain: ETHEREUM
          smartContractAddress: 1.2488751460129641e+48
        - id: USDT-OPTIMISM
          currency: USDT
          blockchain: OPTIMISM
          smartContractAddress: 8.488563199836144e+47
        feePercentages:
        - 0.8
        - 1
        payment_methods:
        - card
        - revolut
        - apple-pay
        - google-pay
  responses:
    BadRequestErrorResponse:
      description: 'Bad request


        A request parameter is invalid.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestError'
          example:
            message: Invalid field 'FieldName'
    ServerErrorResponse:
      description: 'Server error


        An unexpected error occurred.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnexpectedError'
          example:
            errorId: 201768bc-7fab-12ed-a1bb-0232ac120902
            timestamp: 1671481582960
    NotFoundErrorResponse:
      description: Resource cannot be found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFoundError'
          example:
            message: Not found
    DisabledByKillSwitchErrorResponse:
      description: The endpoint is disabled by Kill Switch
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DisabledByKillSwitchError'
          example:
            message: Service is not available
  parameters:
    XApiKey:
      type: apiKey
      in: header
      name: X-API-KEY
      description: "Your API key that you received during integration setup. \nFor more information, see the **Authorization** section."
      required: true
  securitySchemes:
    AccessToken:
      type: http
      scheme: bearer
      description: "Each Business API request must contain an authorization header in the following format to make a call: `Bearer <your_access_token>`.\n\nThe access token will be obtained the first time you set up your application and has an expiration of 40 minutes. \nDuring setup, a `refresh_token` will also be obtained which allows to obtain a new `access_token`.\n\n:::danger\nNever share your client-assertion JWT (JSON web token), `access_token` and `refresh_token` with anyone, as these can be used to access your banking data and initiate transactions.\n:::\n\nAccess tokens can be issued with four security scopes and require a JWT (JSON Web Token) signature to be obtained:\n- `READ`: Permissions for `GET` operations.\n- `WRITE`: Permissions to update counterparties, webhooks, and issue payment drafts.\n- `PAY`: Permissions to initiate or cancel transactions and currency exchanges.    \n- `READ_SENSITIVE_CARD_DATA`: Permissions to retrieve sensitive card details.\n\n  :::warning\n  If you enable the `READ_SENSITIVE_CARD_DATA` scope for your access token, you must set up IP whitelisting. \n  Failing to do so will prevent you from accessing **any** Business API endpoint. \n\n  IP whitelisting means that you must specify an IP or a set of IPs which will be the only IPs from which requests to the API will be accepted. \n  To do so:\n  1. Go to the Revolut Business web app [settings](https://business.revolut.com/settings) → **APIs** → **Business API**.\n  2. Select the corresponding API certificate.\n  3. In **Production IP whitelist**, provide the IP(s) which should be whitelisted.\n      Make sure that the IPs you provide are **not** [local (i.e. private) IP addresses](https://www.okta.com/en-sg/identity-101/understanding-private-ip-ranges/). \n  4. Save the new settings.\n  :::\n\nTo configure your JWT and obtain the refresh and first access tokens, complete the following steps:\n\n  1. [Sign up for a Revolut Business account](https://developer.revolut.com/docs/guides/manage-accounts/get-started/sign-up-for-revolut-business-account)\n  2. [Prepare your Sandbox environment](https://developer.revolut.com/docs/guides/manage-accounts/get-started/prepare-sandbox-environment)\n  3. [Make your first API request](https://developer.revolut.com/docs/guides/manage-accounts/get-started/make-your-first-api-request)"
